server:
  port: 9100

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_user_ms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  config:
    import: optional:configserver:http://localhost:8900

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-63184642.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa91q9sv5HLWNEBA5d7
            client-secret: n9XfQPWsly4vwZdCrJ9G-Q-cmmzob6y9eJ3u7Xjt

        provider:
          okta:
            issuer-uri: https://dev-63184642.okta.com/oauth2/default



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  service-url:
#    defaultZone: http://localhost:8761/eureka



##### acutator configurations :-
management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

###### resilience4j configurations :-
resilience4j:
  circuitbreaker:
    instances:
      getUserCallsRatingAndHotel:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      getUserCallsRatingAndHotel:
        max-attempts: 3
        wait-duration: 3s

  rateLimiter:
    instances:
      getUserCallsRatingAndHotel:
        limitForPeriod: 2         # time period me is se jada no of request nahi lagai jaegi
        limitRefreshPeriod: 1s    # max time period to making requests
        timeoutDuration: 100ns    # agr itne time me request ka response aya to theek ni to thread us reqest ko hata dega



okta:
  oauth2:
    issuer: https://dev-63184642.okta.com/oauth2/default
    audience: api://default
